---
- name: Create user on all the servers
  hosts: dbserver
  tasks:
    - name: Create user
      user:
        name: Anusha
        password: intelliqit
        uid: 1234
        home: /tmp/Anusha
        shell: /bin/bash
        comment: "A normal user"
...
