---
- name: Implementing host scope variables
  hosts: 172.31.91.66 
  tasks:
    - name: Create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...
