---
- name: Implementing tags
  hosts: all
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: 
        - tree_installation
        - never
    - name: Create user
      user:
        name: anu
        password: intelliqit
      tags: user_creation
    - name: Copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...

